name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - run: sudo apt install -y cmake gcc-12 g++-12 ninja-build
      - run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10
      - run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 10
      - run: mkdir build && cd build && cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_BUILD_WERROR=OFF && ninja

  MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_BUILD_WERROR=OFF && make
